##############################################################################################
#
# GitHub Actions configuration file
# 
# Set the required secrets in the build settings of the project:
#   - PACKAGECLOUD_USER
#   - PACKAGECLOUD_KEY
#
##############################################################################################
name: build-debian-package

on: [pull_request, push]

env:
  PACKAGE_NAME: synthetic-monitoring-service
  LICENSE: LGPL-2.1
  VERSION: 0.3
  ARCH: noarch
  AUTHOR: geld.tech
  DESCRIPTION: "Synthetic monitoring service recording availability and latency of services based on Python Flask, Vue.js, and Chart.js"
  REPO_NAME: debs
  DISTRIBUTION: ubuntu/bionic

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distrib: [any/any, ubuntu/bionic, ubuntu/focal]
    steps:
      - uses: actions/checkout@v2

      - name: Export variables containing versions and filename
        run: |
          echo "RELEASE_VERSION=$VERSION"                                               >> $GITHUB_ENV
          echo "BUILD_VERSION=$VERSION.$GITHUB_RUN_NUMBER"                              >> $GITHUB_ENV
          echo "BUILD_DATE=$(date '+%Y%m%d')"                                           >> $GITHUB_ENV
          echo "ARTIFACT_NAME=$PACKAGE_NAME-$VERSION.$GITHUB_RUN_NUMBER_$ARCH.deb"      >> $GITHUB_ENV

      - name: Replace version and build number with the Debian control file
        run: |
          sed -i "s/__VERSION__/$BUILD_VERSION/g" packages/DEBIAN/control
          sed -i "s/__DATE__/$BUILD_DATE/g" packages/DEBIAN/control

      - name: Build the Debian package
        run: |
          cat packages//DEBIAN/control
          dpkg-deb --build packages/
          mv $PACKAGE_NAME.deb $ARTIFACT_NAME

      - name: Output detail on the resulting package for debugging purpose
        run: |
          ls -l $ARTIFACT_NAME
          dpkg --contents $ARTIFACT_NAME
          md5sum $ARTIFACT_NAME
          sha256sum $ARTIFACT_NAME
          export LOCAL_SHA256=$( sha256sum $ARTIFACT_NAME | cut -d " " -f1 )

      - name: Upload artifacts to share data between jobs
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: "*.deb"

      - name: Upload package PackageCloud.io
        uses: danielmundi/upload-packagecloud@v1
        with:
          package-name: ${{ env.ARTIFACT_NAME }}
          packagecloud-username: ${{ secrets.PACKAGECLOUD_USER }}
          packagecloud-repo: ${{ env.REPO_NAME }}
          packagecloud-distrib: ${{ matrix.DISTRIB }}
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
